version: '3.8'

services:
  pms-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=https://api.yoyofun.in/api
        - VITE_PMS_API_URL=https://api.yoyofun.in/api/pms
    container_name: yoyofun-pms
    restart: always
    ports:
      - "9007:80"
